# Generated by Django 3.0.8 on 2021-02-01 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('corre', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Crito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Commer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('monto', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('moneda', models.IntegerField(choices=[[0, 'Bitcoin'], [1, 'XRP'], [2, 'Dogecoin'], [3, 'USD']], default=[2, 'Dogecoin'])),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_email', models.EmailField(max_length=100)),
                ('receptor_name', models.CharField(max_length=100)),
                ('emisor_email', models.EmailField(max_length=100)),
                ('emisor_name', models.CharField(max_length=100)),
                ('monto', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('moneda', models.IntegerField(choices=[[0, 'Bitcoin'], [1, 'XRP'], [2, 'Dogecoin'], [3, 'USD']], default=[2, 'Dogecoin'])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('is_Staff', models.BooleanField(default=False)),
                ('BTC_Count', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Bitcoin ')),
                ('XRP_Count', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de XRP ')),
                ('DOGE_Count', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Dogecoin')),
                ('USD_Count', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Dolares Americanos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
