# Generated by Django 3.0.8 on 2021-02-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_commer',
            name='accion',
            field=models.IntegerField(choices=[[0, 'Comoprar'], [1, 'Vender']], default=0),
        ),
    ]

