# Generated by Django 3.0.8 on 2021-02-02 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripei', '0002_historial_commer_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_commer',
            name='accion',
            field=models.IntegerField(choices=[[0, 'Comoprar'], [1, 'Vender']], default=[0, 'Comoprar']),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DOGE_Count',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Dogecoin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='USD_Count',
            field=models.PositiveIntegerField(default=100000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Dolares Americanos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='XRP_Count',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de XRP '),
        ),
    ]
